# PIC 10C Homework 7, makefile
# Purpose: employee fstream & makefile
# Author: Penggao Gu
# date: 11/28/2022

prog: Employee.h Employee.cpp main.cpp
	g++ -std=c++11 -O3 -o prog Employee.cpp main.cpp
